swagger: '2.0'
info:
  title: Snippets API
  description: Test description
  termsOfService: https://www.google.com/policies/terms/
  contact:
    email: contact@snippets.local
  license:
    name: BSD License
  version: v1
host: localhost:8000
schemes:
- http
basePath: /
consumes:
- application/json
produces:
- application/json
securityDefinitions:
  Basic:
    type: basic
security:
- Basic: []
paths:
  /code/:
    post:
      operationId: code_create
      description: Кодирование и декодирование полученного от транспортного уровня
        сегмента
      parameters:
      - name: data
        in: body
        required: true
        schema:
          type: object
          properties:
            user:
              type: string
            datetime:
              type: string
              format: date-time
            number:
              type: integer
            segment:
              type: string
              format: bytes
      responses:
        '200':
          description: ''
          schema:
            type: object
            properties:
              user:
                type: string
              datetime:
                type: string
                format: date-time
              number:
                type: integer
              segment:
                type: string
                format: bytes
        '400':
          description: ''
      tags:
      - code
    parameters: []
definitions: {}
